shallow_clone: true
build_script:
  - build.bat
test_script:
  - test.bat
artifacts:
  - path: Win32/copy.exe
    name: Copy binary (Win32)

  - path: Win32/paste.exe
    name: Paste binary (Win32)

  - path: Win64/copy.exe
    name: Copy binary (Win64)

  - path: Win64/paste.exe
    name: Paste binary (Win64)
